name: Test Action
on: pull_request

jobs:
        test:
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v2
                        - uses: ./
                          with:
                                  token: ${{ secrets.GITHUB_TOKEN }}
                                  patterns: ./index.js
